version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: kirin
      MONGO_INITDB_ROOT_PASSWORD: asfaqwr123
      MONGO_INITDB_DATABASE: main
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db 
    networks:
      - djangonetwork
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-django-container
    volumes:
      - ./backend:/app 
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost
    command:
      - sh
      - -c
      - python manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge